services:
  database:
    container_name: quarkus_db
    image: postgres
    environment:
      POSTGRES_PASSWORD: quarkus
      POSTGRES_USER: quarkus
      POSTGRES_DB: quarkusdb
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
